/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabolicspiral;

/**
 *
 * @author VADIM
 */
public class ChooseGraphPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChooseGraphPanel
     */
    public ChooseGraphPanel() {
        initComponents();
        this.setSize(900, 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positiveGraphRButton = new javax.swing.JRadioButton();
        negativeGraphRButton = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        positiveGraphRButton.setText("+r");
        positiveGraphRButton.setMaximumSize(new java.awt.Dimension(450, 25));
        positiveGraphRButton.setMinimumSize(new java.awt.Dimension(450, 25));
        positiveGraphRButton.setPreferredSize(new java.awt.Dimension(450, 25));
        add(positiveGraphRButton);

        negativeGraphRButton.setText("-r");
        negativeGraphRButton.setMaximumSize(new java.awt.Dimension(450, 25));
        negativeGraphRButton.setMinimumSize(new java.awt.Dimension(450, 25));
        negativeGraphRButton.setPreferredSize(new java.awt.Dimension(450, 25));
        add(negativeGraphRButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton negativeGraphRButton;
    private javax.swing.JRadioButton positiveGraphRButton;
    // End of variables declaration//GEN-END:variables
}
