/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabolicspiral;

import javax.swing.JRadioButton;

/**
 *
 * @author VADIM
 */
public class ChooseGraphPanel extends javax.swing.JPanel {

    ParabolicSpiralFrame frame;

    /**
     * Creates new form ChooseGraphPanel
     */
    public ChooseGraphPanel(ParabolicSpiralFrame frame) {
        this.frame = frame;
        initComponents();
        this.setSize(900, 25);
    }

    public JRadioButton getNegativeGraphRButton() {
        return negativeGraphRButton;
    }

    public JRadioButton getPositiveGraphRButton() {
        return positiveGraphRButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positiveGraphRButton = new javax.swing.JRadioButton();
        negativeGraphRButton = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        positiveGraphRButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 13)); // NOI18N
        positiveGraphRButton.setForeground(new java.awt.Color(0, 0, 255));
        positiveGraphRButton.setSelected(true);
        positiveGraphRButton.setText("+positive graph");
        positiveGraphRButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positiveGraphRButton.setMaximumSize(new java.awt.Dimension(450, 25));
        positiveGraphRButton.setMinimumSize(new java.awt.Dimension(450, 25));
        positiveGraphRButton.setPreferredSize(new java.awt.Dimension(450, 25));
        positiveGraphRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                positiveGraphRButtonStateChanged(evt);
            }
        });
        add(positiveGraphRButton);

        negativeGraphRButton.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 13)); // NOI18N
        negativeGraphRButton.setForeground(new java.awt.Color(204, 0, 0));
        negativeGraphRButton.setSelected(true);
        negativeGraphRButton.setText("-negative graph");
        negativeGraphRButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        negativeGraphRButton.setMaximumSize(new java.awt.Dimension(450, 25));
        negativeGraphRButton.setMinimumSize(new java.awt.Dimension(450, 25));
        negativeGraphRButton.setPreferredSize(new java.awt.Dimension(450, 25));
        negativeGraphRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                negativeGraphRButtonStateChanged(evt);
            }
        });
        add(negativeGraphRButton);
    }// </editor-fold>//GEN-END:initComponents

    private void positiveGraphRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_positiveGraphRButtonStateChanged
        if (!negativeGraphRButton.isSelected()) {
            positiveGraphRButton.setSelected(true);
            return;
        }
        frame.repaintGraph();
    }//GEN-LAST:event_positiveGraphRButtonStateChanged

    private void negativeGraphRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_negativeGraphRButtonStateChanged
        if (!positiveGraphRButton.isSelected()) {
            negativeGraphRButton.setSelected(true);
            return;
        }
        frame.repaintGraph();
    }//GEN-LAST:event_negativeGraphRButtonStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton negativeGraphRButton;
    private javax.swing.JRadioButton positiveGraphRButton;
    // End of variables declaration//GEN-END:variables
}
