/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabolicspiral;

import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author VADIM
 */
public class GraphModifierPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraphModifierPanel
     */
    public GraphModifierPanel() {
        initComponents();
        this.setSize(900, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        constLabel = new javax.swing.JLabel();
        constField = new javax.swing.JFormattedTextField();
        fiMinLabel = new javax.swing.JLabel();
        fiMinField = new javax.swing.JFormattedTextField();
        fiMaxLabel = new javax.swing.JLabel();
        fiMaxField = new javax.swing.JFormattedTextField();
        rangeXLabel = new javax.swing.JLabel();
        rangeXSpinner = new javax.swing.JSpinner();
        rangeYLabel = new javax.swing.JLabel();
        rangeYSpinner = new javax.swing.JSpinner();
        stepLabel = new javax.swing.JLabel();
        stepField = new javax.swing.JFormattedTextField();
        drawGraphButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 100));
        setMinimumSize(new java.awt.Dimension(600, 100));
        setPreferredSize(new java.awt.Dimension(1200, 100));
        setLayout(new java.awt.GridBagLayout());

        constLabel.setText("const a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(constLabel, gridBagConstraints);

        constField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        constField.setText("2");
        constField.setMinimumSize(new java.awt.Dimension(50, 22));
        constField.setPreferredSize(new java.awt.Dimension(50, 30));
        add(constField, new java.awt.GridBagConstraints());

        fiMinLabel.setText("fi min: PI *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(fiMinLabel, gridBagConstraints);

        fiMinField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        fiMinField.setText("0");
        fiMinField.setMinimumSize(new java.awt.Dimension(50, 22));
        fiMinField.setPreferredSize(new java.awt.Dimension(50, 30));
        add(fiMinField, new java.awt.GridBagConstraints());

        fiMaxLabel.setText("fi max: PI *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(fiMaxLabel, gridBagConstraints);

        fiMaxField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        fiMaxField.setText("4");
        fiMaxField.setMinimumSize(new java.awt.Dimension(50, 22));
        fiMaxField.setPreferredSize(new java.awt.Dimension(50, 30));
        add(fiMaxField, new java.awt.GridBagConstraints());

        rangeXLabel.setText("range x:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(rangeXLabel, gridBagConstraints);

        rangeXSpinner.setModel(new javax.swing.SpinnerNumberModel(450, 0, 450, 1));
        add(rangeXSpinner, new java.awt.GridBagConstraints());

        rangeYLabel.setText("range y:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(rangeYLabel, gridBagConstraints);

        rangeYSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 250, 1));
        add(rangeYSpinner, new java.awt.GridBagConstraints());

        stepLabel.setText("step:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        add(stepLabel, gridBagConstraints);

        stepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        stepField.setText("1");
        stepField.setPreferredSize(new java.awt.Dimension(50, 30));
        add(stepField, new java.awt.GridBagConstraints());

        drawGraphButton.setText("Draw");
        drawGraphButton.setPreferredSize(new java.awt.Dimension(300, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 5.0;
        add(drawGraphButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField constField;
    private javax.swing.JLabel constLabel;
    private javax.swing.JButton drawGraphButton;
    private javax.swing.JFormattedTextField fiMaxField;
    private javax.swing.JLabel fiMaxLabel;
    private javax.swing.JFormattedTextField fiMinField;
    private javax.swing.JLabel fiMinLabel;
    private javax.swing.JLabel rangeXLabel;
    private javax.swing.JSpinner rangeXSpinner;
    private javax.swing.JLabel rangeYLabel;
    private javax.swing.JSpinner rangeYSpinner;
    private javax.swing.JFormattedTextField stepField;
    private javax.swing.JLabel stepLabel;
    // End of variables declaration//GEN-END:variables
}
